# Generated by Django 3.0.6 on 2022-06-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='deleted_at',
        ),
    ]
